name: dynode
channels:
  - pytorch
  - defaults
dependencies:
  - absl-py=0.9.0
  - cudatoolkit=10.2
  - imageio=2.8.0
  - pillow=7.0.0
  - pyparsing=2.4.6
  - pip
  - python=3.7
  - pytorch=1.5.0
  - scikit-image=0.16.2
  - torchvision=0.6
  - pip:
    - termcolor
    - dm_control
    - git+https://github.com/1nadequacy/dmc2gym.git
    - gym==0.17.1
    - imageio-ffmpeg==0.4.1
    - mujoco-py==2.0.2.10
    - numpy==1.16.1
    - tb-nightly
    - tensorboard==1.14.0
